//! Central Tauri command registry.
//!
//! Keeping the generated handler in its own module makes `lib.rs` responsible
//! for application bootstrap only.  Command implementations remain grouped by
//! domain under `modules::tauri_commands`.

use crate::modules::builtin_emoji::sync_builtin_emoji;
use crate::modules::easytier_advanced_commands::{
    clear_lobby_easytier_advanced_config, get_global_easytier_advanced_config,
    get_lobby_easytier_advanced_config, save_global_easytier_advanced_config,
    save_lobby_easytier_advanced_config,
};
use crate::modules::mc_lan_bridge::{start_mc_lan_broadcast, stop_mc_lan_broadcast};
use crate::modules::minecraft_discovery::{
    measure_peers_latency, query_minecraft_server, scan_minecraft_servers,
};
use crate::modules::native_capture::{
    native_capture_frame, native_capture_sources, native_capture_start, native_capture_stop,
};
use crate::modules::native_microphone::{
    native_microphone_devices, native_microphone_read, native_microphone_start,
    native_microphone_stop, native_microphone_supported, recording_system_audio_start,
    report_audio_diagnostic,
};
use crate::modules::quark_support::quark_support;
use crate::modules::remote_control::{
    authorize_remote_input, remote_inject_input, revoke_remote_input,
};
use crate::modules::screen_recording::{
    recording_choose_directory, recording_create, recording_finish, recording_get_directory,
    recording_reset_directory, recording_write,
};
use crate::modules::tauri_commands::*;
use crate::modules::voice_ice::voice_ice_server;
use crate::{
    apply_hotkeys, greet, minimize_main_window_to_tray, open_devtools, set_tray_menu_texts,
};

/// Build the application command handler for the selected Tauri runtime.
pub fn handler<R: tauri::Runtime>() -> impl Fn(tauri::ipc::Invoke<R>) -> bool {
    tauri::generate_handler![
        sync_builtin_emoji,
        crate::modules::secret_store::protect_lobby_password,
        crate::modules::secret_store::export_lobby_password,
        greet,
        open_devtools,
        create_lobby,
        join_lobby,
        leave_lobby,
        toggle_mic,
        set_mic_enabled,
        open_microphone_privacy_settings,
        reset_microphone_permission,
        mute_player,
        mute_all,
        get_config,
        update_config,
        save_opacity,
        get_audio_devices,
        get_app_state,
        get_current_lobby,
        get_players,
        get_mic_status,
        get_global_mute_status,
        is_player_muted,
        get_network_status,
        get_virtual_ip,
        get_peer_connection_types,
        set_always_on_top,
        toggle_mini_mode,
        set_window_opacity,
        send_signaling_message,
        broadcast_status_update,
        send_heartbeat,
        force_stop_easytier,
        cancel_lobby_connecting,
        check_virtual_adapter,
        ping_virtual_ip,
        check_udp_port,
        is_admin,
        restart_as_admin,
        save_window_position,
        exit_app,
        add_player_domain,
        remove_player_domain,
        get_folder_name,
        get_folder_info,
        list_directory_files,
        read_file_bytes,
        write_file_bytes,
        select_folder,
        select_file,
        select_save_location,
        select_file_share_download_folder,
        get_file_share_download_dir,
        set_file_share_download_dir,
        get_file_share_download_path,
        save_file,
        save_chat_image,
        read_file,
        delete_file,
        extract_zip,
        open_external_url,
        open_file_location,
        open_folder,
        start_file_server,
        stop_file_server,
        check_file_server_status,
        add_shared_folder,
        remove_shared_folder,
        get_local_shares,
        cleanup_expired_shares,
        get_remote_shares,
        get_remote_files,
        verify_share_password,
        get_download_url,
        diagnose_file_share_connection,
        download_remote_file,
        cancel_remote_download,
        export_logs,
        test_node_latency,
        download_remote_batch,
        detect_security_software,
        prepare_p2p_chat_identity,
        prepare_signaling_identity,
        sign_signaling_registration,
        configure_p2p_chat,
        update_p2p_chat_peers,
        stop_p2p_chat,
        select_chat_attachment,
        prepare_chat_image,
        fetch_chat_attachment,
        save_chat_attachment,
        download_danmaku_attachment,
        preview_spreadsheet_attachment,
        preview_office_attachment,
        transcribe_voice_message,
        send_p2p_chat_message,
        get_p2p_chat_messages,
        clear_p2p_chat_messages,
        open_screen_viewer_window,
        open_danmaku_window,
        close_danmaku_window,
        set_danmaku_ignore_cursor,
        danmaku_cursor_pos,
        save_danmaku_image,
        open_game_hud_window,
        close_game_hud_window,
        set_gamehud_ignore_cursor,
        gamehud_cursor_pos,
        open_log_folder,
        open_log_file,
        get_log_file_path,
        read_log_file,
        set_avatar_data,
        clear_avatar_cache,
        save_settings,
        get_settings,
        get_compliance_consent,
        accept_compliance,
        set_auto_start,
        check_auto_start,
        reset_config_to_default,
        save_voice_volume,
        export_config,
        import_config,
        restart_app_with_gpu_settings,
        save_exit_node_advanced_config,
        get_exit_node_advanced_config,
        save_global_easytier_advanced_config,
        get_global_easytier_advanced_config,
        save_lobby_easytier_advanced_config,
        get_lobby_easytier_advanced_config,
        clear_lobby_easytier_advanced_config,
        scan_minecraft_servers,
        query_minecraft_server,
        measure_peers_latency,
        start_mc_lan_broadcast,
        stop_mc_lan_broadcast,
        set_tray_menu_texts,
        minimize_main_window_to_tray,
        authorize_remote_input,
        remote_inject_input,
        revoke_remote_input,
        apply_hotkeys,
        recording_create,
        recording_get_directory,
        recording_choose_directory,
        recording_reset_directory,
        recording_write,
        recording_finish,
        recording_system_audio_start,
        native_microphone_supported,
        voice_ice_server,
        quark_support,
        report_audio_diagnostic,
        native_microphone_devices,
        native_microphone_start,
        native_microphone_read,
        native_microphone_stop,
        native_capture_sources,
        native_capture_start,
        native_capture_frame,
        native_capture_stop,
    ]
}
